version: '3.1'

services:
  db:
    container_name: treesdb
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: trees
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "7432:5432"